name: Docker Image CI

on:
  push:
    branches: [ main, steph0de-patch-1 ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag urlgen-sveltejs:$(date +%s)
